name: 'Cache node modules'
# description: 'Greet someone'
runs:
  using: 'composite'
  steps:
    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v2
      if: ${{ !env.ACT }}
      with:
        main-branch-name: 'develop'

    - name: Cache node modules
      id: dependency_cache
      uses: actions/cache@v2
      if: ${{ !env.ACT }}
      env:
        cache-name: cache-node-modules
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install yarn
      run: npm install yarn -g
      shell: bash

    - name: Install packages
      run: yarn install --frozen-lockfile
      shell: bash
