name: CI Tests

# The current branch that triggered the workflow run.
# e.g feature/api-admin, develop
env:
  BRANCH_NAME: ${GITHUB_REF#refs/heads/}

on: 
  push:
    branches: [ develop, feature/ci-tests ]
  pull_request:
    branches: [ develop ]
  
jobs:
  test-affected:
    uses: ./.github/workflows/default.yml
    with:
      type: 'affected'
  #   uses: joshuabrink1/graduates/.github/workflows/cache.yml@develop


  test-all:
    uses: ./.github/workflows/default.yml
    with:
      type: 'all'


  # unit-test:
  #   needs: cache
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: npx nx affected:test --base=$BRANCH_NAME
      
  # e2e-test:
  #   needs: cache
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: npx nx affected:e2e --base=$BRANCH_NAME
    
  # lint-test:
  #   needs: cache
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: npx nx affected:lint --base=$BRANCH_NAME

  # build-test:
  #   needs: cache
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: npx nx affected:build --base=$BRANCH_NAME


  # cypress-e2e-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Derive appropriate SHAs for base and head for `nx affected` commands
  #       uses: nrwl/nx-set-shas@v2
  #       if: ${{ !env.ACT }}
  #       with:
  #         main-branch-name: 'develop'
  #     - name: Node Setup
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '16'
  #     - run: npm install
  #     - run: npx nx affected:e2e --base=${{ env.NX_HEAD }}
  # deploy:
#   needs: test