# name: Nx Standard Use Case
# on: [push, pull_request]
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Node Setup
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'
#       - run: npm install
#       - run: npx nx affected:lint
#       - run: npx nx affected:build
#       - run: npx nx affected:test
#   cypress-e2e-test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#       # - name: Derive appropriate SHAs for base and head for `nx affected` commands
#       #   uses: nrwl/nx-set-shas@v2
#       #   with:
#       #     main-branch-name: 'develop'
#       - name: Node Setup
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'
#       - run: npm install
#       - run: npx nx affected:e2e --base=develop
#   # deploy:
#   #   needs: test
name: Nx Distributed Tasks
on: push
jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        if: ${{ !env.ACT }}
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-feature-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-feature-${{ env.cache-name }}-
            ${{ runner.os }}-feature-
            ${{ runner.os }}-
     
      - run: npm install
distributed-task:
    runs-on: ubuntu-latest
    needs: install-deps
    strategy:
      matrix:
        target: ['test', 'lint', 'build']
        jobIndex: [1, 2, 3, 4]
    env:
      jobCount: 4
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --no-tags --prune --depth=1 origin develop
      - name: Cache node modules
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('yarn.lock') }}
      - run: node ./tools/scripts/run-many.js ${{ matrix.target }} ${{ matrix.jobIndex }} ${{ env.jobCount }} $GITHUB_REF