name: CI Tests

# The current branch that triggered the workflow run.
# e.g feature/api-admin, develop
env:
  BRANCH_NAME: ${GITHUB_REF#refs/heads/}

on: 
  push:
    branches: [ develop, $BRANCH_NAME ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
  
jobs:
  cache:
    uses: joshuabrink1/graduates/.github/workflows/cache.yml@develop

  test-changed:
    needs: cache
    runs-on: ubuntu-latest
    steps:
      - run: npx nx affected:lint --base=$BRANCH_NAME 
      - run: npx nx affected:test --base=$BRANCH_NAME
      - run: npx nx affected:build --base=$BRANCH_NAME

  test-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        if: ${{ !env.ACT }}
        with:
          main-branch-name: 'develop'

      - name: Cache node modules
        id: dependency_cache
        uses: actions/cache@v2
        if: ${{ !env.ACT }}
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install yarn
        run: npm install yarn -g

      - name: Install packages
        run: yarn install --frozen-lockfile
        
      - run: yarn nx run-many --target=lint --all
      - run: yarn nx run-many --target=test --all
      - run: yarn nx run-many --target=build --all
  # unit-test:
  #   needs: cache
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: npx nx affected:test --base=$BRANCH_NAME
      
  # e2e-test:
  #   needs: cache
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: npx nx affected:e2e --base=$BRANCH_NAME
    
  # lint-test:
  #   needs: cache
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: npx nx affected:lint --base=$BRANCH_NAME

  # build-test:
  #   needs: cache
  #   runs-on: ubuntu-latest
  #   steps:
  #   - run: npx nx affected:build --base=$BRANCH_NAME


  # cypress-e2e-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Derive appropriate SHAs for base and head for `nx affected` commands
  #       uses: nrwl/nx-set-shas@v2
  #       if: ${{ !env.ACT }}
  #       with:
  #         main-branch-name: 'develop'
  #     - name: Node Setup
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '16'
  #     - run: npm install
  #     - run: npx nx affected:e2e --base=${{ env.NX_HEAD }}
  # deploy:
#   needs: test